To/#158 osm model
ie3-institute/PowerSystemUtils pull request #162
Opened 2021-12-01 10:44 UTC by t-ober

Proposal for #158 

Will most likely need some more extension later on.

2021-12-01 10:48 UTC, t-ober commented
Did not change `QunatityUtils` or `QuantityUtilsSpec` maybe they show up in the diff because of adding spotlessApply to the scala.

2021-12-02 11:53 UTC, ckittl requested changes

2021-12-02 11:53 UTC, ckittl commented on src/main/scala/edu/ie3/util/osm/OsmModel.scala
> +      case way: ClosedWay if way.containsKeyValuePair(landuse, landUseValues) =>
Here again. Does the restriction to closed ways make sense?

2021-12-02 11:53 UTC, ckittl commented on src/main/scala/edu/ie3/util/osm/TagUtils.scala
> +    )
As discussed orally: Please leave out here and implement in OSMoGrid

2021-12-02 11:53 UTC, ckittl commented on src/main/scala/edu/ie3/util/osm/OsmModel.scala
> +    ways.filter(way => way.containsKeyValuePair(highway, highWayValues))
As discussed orally: If the "allowed" values provided in `TagUtils` are not in this project anymore, the outline of the method needs adaption.

2021-12-02 11:53 UTC, ckittl commented on src/main/scala/edu/ie3/util/osm/OsmModel.scala
> +      case way: ClosedWay if way.containsKeyValuePair(landuse, landUseValues) =>
As discussed orally: If the "allowed" values provided in `TagUtils` are not in this project anymore, the outline of the method needs adaption.

2021-12-02 14:30 UTC, t-ober commented on docs/OsmModel.puml
> +end note
If a roundabout is considered a `ClosedWay` we can't return list of `OpenWay`

2021-12-02 14:44 UTC, t-ober commented on docs/OsmModel.puml
> +    role: String
It's an optional descriptive field which is user-defined so that won't work

2021-12-02 18:30 UTC, ckittl approved these changes

2021-12-02 18:30 UTC, merged