Re-implementing GeoUtils back in Java
ie3-institute/PowerSystemUtils pull request #259
Opened 2022-05-18 20:46 UTC by sebastian-peter

Resolves #253

2022-05-19 07:55 UTC, sebastian-peter commented on src/main/java/edu/ie3/util/geo/GeoUtils.java
> +  public static ComparableQuantity<Length> totalLengthOfLineString(LineString lineString) {
@sonatype-lift ignore

2022-05-19 07:55 UTC, sebastian-peter commented on src/main/java/edu/ie3/util/geo/GeoUtils.java
> +  public static ComparableQuantity<Length> totalLengthOfLineString(LineString lineString) {
@sonatype-lift ignore

2022-05-24 06:43 UTC, t-ober requested changes
Thanks a lot for taking this over 😍   
Looks pretty solid

2022-05-24 06:43 UTC, t-ober commented on src/main/java/edu/ie3/util/geo/GeoUtils.java
> +        ArrayUtils.addAll(new Coordinate[] {safeCoord1}, c2));
```suggestion
        ArrayUtils.addAll(safeCoord1, c2));
```

shouldn't this suffice?

2022-05-24 07:49 UTC, sebastian-peter commented on src/main/java/edu/ie3/util/geo/GeoUtils.java
> +        ArrayUtils.addAll(new Coordinate[] {safeCoord1}, c2));
Found an even better solution imho :)

2022-05-24 12:15 UTC, t-ober approved these changes

2022-05-24 12:16 UTC, merged