transfer quantity matchers from SIMONA
ie3-institute/PowerSystemUtils pull request #362
Opened 2023-05-09 14:45 UTC by danielfeismann

resolves #361

2023-07-19 09:50 UTC, sebastian-peter commented
I have one critical remark here: These matchers are supposed to be solely used in tests. Here, they are now transferred into "main" code, which is also available e.g. in SIMONA, where the dependency is added via `implementation` in gradle (same for any other project where PSU are not added _just_ for tests, i.e. practically all).
This means, that when compiling SIMONA, these classes are compiled and kept with all other "main" code as well, which they technically shouldn't be. Code that is only needed for tests does not have to be available in main. 

So I'm not fundamentally opposed to making the quantity matchers more universally available, but this might be something to consider. Also, since we're moving towards using squants more, this might not be a something that we absolutely need?

2024-02-07 13:17 UTC, sebastian-peter commented
Also a reminder that comparison matching with quantities can be done via `a should be < b`, `a should be <= b` etc as well.

2024-06-10 12:22 UTC, jo-bao requested changes
Overall it looks good to me! Just a few minor points.

2024-06-10 12:22 UTC, jo-bao commented on CHANGELOG.md
> +-   Transfer QuantityMatchers from SIMONA [#361](https://github.com/ie3-institute/PowerSystemUtils/issues/361)
There is a tab too much.

2024-06-10 12:22 UTC, jo-bao commented on src/main/scala/edu/ie3/util/quantities/QuantityMatchers.scala
> +    *   Compare function (lhs, rhs) => Condition
I am not sure, if I would call it "Condition"

2024-06-11 09:58 UTC, danielfeismann commented on CHANGELOG.md
> +-   Transfer QuantityMatchers from SIMONA [#361](https://github.com/ie3-institute/PowerSystemUtils/issues/361)
Good catch!

2024-06-12 11:36 UTC, danielfeismann commented
Since with [this commit](https://github.com/ie3-institute/simona/pull/82/commits/ef5adeec9da14d8ffa2e31338eb8db98f382e8d0) the proposed changes are no longer direclty needed in SIMONA we decided to close this PR.

2024-06-12 11:36 UTC, closed without merging