Added a semantic equality check for Quantities
ie3-institute/PowerSystemUtils pull request #45
Opened 2020-09-07 15:06 UTC by mia-krause

resolves #200, needed for PowerSystemDataModel#178

I only added the equals(Quantity, Quantity) method. However, I am unsure if the considerably*Equal methods became obsolete by this and the framework change, as there are no DoubleQuantities anymore.

2020-09-11 20:08 UTC, johanneshiry commented
@mia-krause I've not worked with the new quantities implementation so much but what exactly has changed there? What is the replacement for DoubleQuantity? Is there any replacement at all?

2020-09-13 14:30 UTC, ckittl commented
I would really like you to wait for #44 to be closed, so that you may include your changes in change log document as well.

2020-10-02 07:05 UTC, johanneshiry requested changes
In general, this looks good to me. But as sonarqube points out there are two bugs included, hat throw a NullPointerException. Is this by purpose or can you fix this?

see [report](
https://simona.ie3.e-technik.tu-dortmund.de/sonar/project/issues?id=edu.ie3%3Autils&open=AXTEmrYN9gLJI2-HpSd_&pullRequest=45&resolved=false&sinceLeakPeriod=true&types=BUG) for details

2020-10-08 11:03 UTC, ckittl approved these changes

2020-10-08 11:29 UTC, johanneshiry approved these changes

2020-10-08 11:29 UTC, merged